services:

  database:
    image: mysql:8.4
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: traccar
      MYSQL_USER: traccar
      MYSQL_PASSWORD: traccar
    volumes:
      - ./mysql-data:/var/lib/mysql

  traccar:
    image: traccar/traccar:latest
    restart: unless-stopped
    depends_on:
      - database
    environment:
      CONFIG_USE_ENVIRONMENT_VARIABLES: "true"
      DATABASE_DRIVER: com.mysql.cj.jdbc.Driver
      DATABASE_URL: >-
        jdbc:mysql://database:3306/traccar
        ?zeroDateTimeBehavior=round
        &serverTimezone=UTC
        &allowPublicKeyRetrieval=true
        &useSSL=false
        &allowMultiQueries=true
        &autoReconnect=true
        &useUnicode=yes
        &characterEncoding=UTF-8
        &sessionVariables=sql_mode=''
      DATABASE_USER: traccar
      DATABASE_PASSWORD: traccar
    ports:
      - "8082:8082"
      - "5000-5500:5000-5500"
    volumes:
      - ./logs:/opt/traccar/logs

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - database
